name : Hello World Worflow

on:
	push:
		branches:
			- master
	pull_request:
		branches:
			- master
	workflow_dispatch:

jobs:
	hello:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v2
			- 	name : hello_world
				run : echo "Hello world my name is Varad Gupta"
				shell : bash
	goodbye:
		runs-on: ubuntu-latest
		steps:
			- 	name : goodbye_world
				run : echo "Goodbye world my name is Varad Gupta"
				shell : bash
