name: New_issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
       - name: "install jq"
         run: sudo apt-get update && sudo apt-get install -y jq
         
       - name: "new issue opened"
         run: echo  '${{ toJSON(github.event) }}' | jq
         shell: bash
       - name: Create comment
         uses: peter-evans/create-or-update-comment@v3
         with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Thanks for opening this new issue.
          reactions: '+1'
