name: New_issue

on:
  issues:
    types: [opened]

jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
       - name: "install jq"
         run: sudo apt-get update && sudo apt-get install -y jq
         
       - name: "new issue opened"
         run: echo  '${{ toJSON(github.event) }}' | jq
         shell: bash
       - name: Create comment
         uses: actions/first-interaction@v1
         with:
              repo-token: ${{ secrets.GITHUB_TOKEN }}
              issue-message: "Message that will be displayed on users' first issue #${{github.event.issue.number}}"
