name : Python Linting

on : 
    [push, pull_request, pull_request_target]

jobs:
    python-linting-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
            - name: Super-Linter
              uses: super-linter/super-linter@v6.5.1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                VALIDATE_ALL_CODEBASE: false  # Optional: Only lint files changed in the commit
                DEFAULT_BRANCH: master
    