name : Python Linting

on : 
    [push, pull_request, pull_request_target]

jobs:
    python-linting-code:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Super-Linter
              uses: super-linter/super-linter@v6.5.1
              env:
                GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
                DEFAULT_BRANCH: master
                VALIDATE_ALL_CODEBASE: true
    