name : New Workflow

on :
    issues:
        types:
            - opened
            - labeled
    push:
        branches:
            master

jobs:
    build:
        name:  build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Run a sample github actions
              run: echo "This workfow ran successfully"
